os: osx
osx_image: xcode7.3
rvm:
  - 2.2.5
before_install:
  - gem update --system
  - gem --version
install:
  - bundle install
  - bundle exec rake install
script: bundle exec rake
env:
  - TRAVIS=true
